Added PoS Validator
ahmed-alllam/AlphaLogos pull request #15
Opened 2023-10-19 08:41 UTC by Hamdy1337

The program processes a string and parses it to validate whether it is in the products of sum (PoS) format according to the following rules:

- When matched with a `(` it sets a boolean variable `isopen` to `true`.
- While `isopen` is `true`, it matches singular (not multiplied) alphabetical characters that might be followed by the `NOT` operator `'` and separated by a `+` all while ignoring whitespaces.
- While `isopen` is `false`, the parser looks for the following an asterisk, empty-space, or a whitespace to ensure that the next opoeration is a product.
- There is a code in the background that ensures the balance of parentheses.

This PR resolves #5

2023-10-19 10:22 UTC, ahmed-alllam requested changes

2023-10-19 10:22 UTC, ahmed-alllam commented on src/logic_utils/PoS_validator.h
> + #ifndef POS_EXPRESSION_H
Remove this space at the beginning

2023-10-19 10:22 UTC, ahmed-alllam commented on tests/test_PoS_validator.cpp
> +#include "../src/logic_utils/PoS_validator.h"   // Adjust the path accordingly
Remove this comment (which is from the tests md guide)

2023-10-19 10:22 UTC, ahmed-alllam commented on tests/test_PoS_validator.cpp
I've observed that a majority of the tests are focused on valid cases, with only a small subset (5 tests) addressing invalid scenarios. It's generally advisable to have a more balanced or even a heavier emphasis on testing invalid cases, given their potential to be more numerous and the **higher cost associated with false positives compared to false negatives**.

2023-10-19 10:22 UTC, ahmed-alllam commented on src/logic_utils/PoS_validator.cpp
> +    int parenCount = 0;  // To track unmatched parentheses
The variable names within this code snippet are quite ambiguous and lack meaningful descriptions, which could lead to confusion during code maintenance or review. It's advisable to use more descriptive and self-explanatory variable names to enhance code readability and maintainability. For instance:

1. `isOpen` could be renamed to something like `isParenthesisOpen` to better reflect its purpose.
2. `charCount` might be more descriptive as `charInsideParenCount` or simply `charCountInParen`.
3. `lastWasApostrophe` could be renamed to `lastCharWasApostrophe` for clarity.
4. `parenCount` is relatively clear, but could be further descriptive like `unmatchedParenCount` to reflect its role in tracking unmatched parentheses.

2023-10-19 10:22 UTC, ahmed-alllam commented on src/logic_utils/PoS_validator.cpp
> +bool isPoSExpression(const string& expr) {
I think `isValidPoS` is a better naming. change it here as well as in the headers file.

2023-10-19 10:22 UTC, ahmed-alllam commented on src/logic_utils/PoS_validator.cpp
I noticed that the function returns `false` when encountering an invalid condition. A more informative approach could be to throw exceptions with descriptive messages instead. This would provide clearer insights into the nature of the error, aiding in debugging and ensuring better error handling at the call site.

Example:
```c++
if (c == '(') return false;  // No nested parentheses
// could be replaced with:
if (c == '(') throw std::invalid_argument("Nested parentheses are not allowed");
```

2023-10-19 23:18 UTC, Hamdy1337 commented on src/logic_utils/PoS_validator.cpp
This will be done when both functions `PoS_validator` and `SoP_validator` are used in the same program to eliminate redundant programming.

2023-10-22 12:48 UTC, ahmed-alllam approved these changes

2023-10-22 12:49 UTC, merged